language: android
jdk: oraclejdk8

env:
  global:
  - ANDROID_API=28
  - ANDROID_BUILD_TOOLS=28

android:
  components:
  - tools
  - tools # Running this twice get's the latest build tools (https://github.com/codepath/android_guides/wiki/Setting-up-Travis-CI)
  - platform-tools
  - android-${ANDROID_API}
  - build-tools-${ANDROID_BUILD_TOOLS}
  - extra

before_script:
  - cd frontend

script:
  - ./gradlew clean test build